import:
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-base-r4.1.yml
    mode: deep_merge_prepend
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-dom0-r4.1.yml
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-vms-r4.1.yml

jobs:
  include:
    - env:
       - ENABLE_SLOW_TESTS=1
      language: python
      python: '3.6'
      install:
       - pip install --quiet -r ci/requirements.txt
      script:
       - python setup.py build
       - PYTHONPATH=test-packages pylint qubesadmin
       - ./run-tests
      after_success:
       - codecov
    - env:
       - ENABLE_SLOW_TESTS=1
      language: python
      python: '3.7'
      install:
       - pip install --quiet -r ci/requirements.txt
      script:
       - python setup.py build
       - PYTHONPATH=test-packages pylint qubesadmin
       - ./run-tests
      after_success:
       - codecov
    - env:
       - ENABLE_SLOW_TESTS=1
      language: python
      python: '3.8'
      install:
       - pip install --quiet -r ci/requirements.txt
      script:
       - python setup.py build
       - PYTHONPATH=test-packages pylint qubesadmin
       - ./run-tests
      after_success:
       - codecov
    - stage: deploy
      env: DIST_DOM0=fc32
      script:
       - ~/qubes-builder/scripts/travis-deploy
